apiVersion: kaptain.org/1.18
kind: basic-quality-and-versioning

spec:
  global:
    projectName:
      stripRepositoryNamePrefix: test
  layers:
    - ghcr.io/kube-kaptain/layer/layer-aws-eks-cluster-management:[1.6]
  main:
    quality:
      branches:
        blockSlashes: true
      commits:
        blockConventional: true
