FROM scratch

LABEL version="1.0.3"
LABEL project.name="aws-eks-cluster-management"
LABEL image.tag="1.0.3-PRERELEASE-release-change-data"
LABEL image.name="kaptain-test-repos/aws/aws-eks-cluster-management"
LABEL image.uri="ghcr.io/kaptain-test-repos/aws/aws-eks-cluster-management:1.0.3-PRERELEASE-release-change-data"

COPY Dockerfile /Dockerfile
COPY release-change-data-1.0.3.yaml /release-change-data-1.0.3.yaml
