name: EKS Cluster Management Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/aws-eks-cluster-management.yaml@one
    permissions:
      contents: write
      packages: write
      checks: write
