name: EKS Cluster Management Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/aws-eks-cluster-management.yaml@fix-account-id-quoting
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      docker-platform: linux/amd64,linux/arm64
